<a href="https://colab.research.google.com/github/dipakwaghamode/Python/blob/main/All_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PANDAS

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series()
s

Series([], dtype: object)

In [ ]:
l = [10, 20, 30, 40, 50] # list
pd.Series(l)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
## Using np array
import numpy as np
a = np.array(["a", "b", "c", "d",""])
b = ([10, 11, 12, 13, 14])
pd.Series(a, b)

10    a
11    b
12    c
13    d
14
dtype: object

In [ ]:
# Adding labels in series
age = pd.Series([10, 11, 12], index = ["Sudiptha", "Akhila", "Rohit"])
age

Sudiptha    10
Akhila      11
Rohit       12
dtype: int64

In [ ]:
import pandas as pd
my_set=[68,72,82,55,95]
df=pd.DataFrame(list(my_set),columns=['Weight'],index=['Shailesh','Sai','Harsha','Jagdeesh','Mujeeb'])
print(df)

          Weight
Shailesh      68
Sai           72
Harsha        82
Jagdeesh      55
Mujeeb        95

In [ ]:
from ast import Name
import pandas as ab
a_set = {10,20},{30,40}
a=ab.DataFrame(list (a_set),index=[['dipak','Sai'],['Jagdeesh','Mujeeb']])
print(a)

                 0   1
dipak Jagdeesh  10  20
Sai   Mujeeb    40  30

In [ ]:
import pandas as ab

# Use a list instead of a set for ordered values
a_set = [10, 20, 30]
a = ab.DataFrame(a_set, columns=['Weight'], index=['dipak', 'Sai', 'Harsha'])

# Print the DataFrame with formatted output
print("Name     Weight")
for index, row in a.iterrows():
    print(f"{index: <8} {row['Weight']}")

Name     Weight
dipak    10
Sai      20
Harsha   30

In [ ]:
import pandas as ab

# Define a list of tuples for the data
a_set = {10, 20,30, 40}

# Create the DataFrame with a single index for the rows
index = ['dipak', 'Sai', 'Jagdeesh', 'Mujeeb']

# Create the DataFrame from the data and set the index
a = ab.DataFrame(a_set, columns=[0], index=index)

# Print the DataFrame
print(a)

           0
dipak     40
Sai       10
Jagdeesh  20
Mujeeb    30

In [ ]:
import pandas as ab

# Create the data as a list of values
data = ([10, 20], [30, 40])

# Define the index
index = ['dipak', 'Sai', 'Jagdeesh', 'Mujeeb']

# Create the DataFrame
a = ab.DataFrame(data, columns=[0], index=index)

# Print the DataFrame
print(a)

ValueError: 1 columns passed, passed data had 2 columns

In [ ]:
import pandas as ab

# Define the data as a list of tuples
a_set = [(10, 20), (30, 40)]

# Flatten the data into a single list
flattened_data = [item for sublist in a_set for item in sublist]

# Define the index
index = ['dipak', 'Sai', 'Jagdeesh', 'Mujeeb']

# Create the DataFrame
a = ab.DataFrame(flattened_data, columns=[0], index=index)

# Print the DataFrame
print(a)

           0
dipak     10
Sai       20
Jagdeesh  30
Mujeeb    40

In [ ]:
import pandas as pd
data={'name':['Sam','Arvind','Sai'],'Percentage':[90,95,85],'ID':[1,2,3]}
df=pd.DataFrame(data,index=[1,2,4])
print(df)

     name  Percentage  ID
1     Sam          90   1
2  Arvind          95   2
4     Sai          85   3

In [ ]:
l = [10, 20, 30]
s = pd.Series(l, index = [0, 1,2])
print(s)

0    10
1    20
2    30
dtype: int64

In [ ]:
import pandas as pd
import numpy as np

a=np.array([10,20,30,40])
s=pd.Series(a,index=['A','B','C','D'])
print(s)
print(s.shape)
print(s.size)
print(s.memory_usage())
print(s.ndim)
print(type(a))

A    10
B    20
C    30
D    40
dtype: int64
(4,)
4
64
1
<class 'numpy.ndarray'>

In [ ]:
###Commited
'''import pandas as pd

df1=pd.DataFrame({'Player':['Player1','Player2','Player3','Player4'],
                  'Scores':[88,92,63,22]})

df2=pd.DataFrame({'Player':['Player1','Player2','Player4'],
                  'Wickets':[0,1,5]})

df3=pd.DataFrame({'Player':['Player4','Player2','Player3'],
                  'Catch' :[0,2,1]})

df4=pd.DataFrame({'Player':['Player4','Player5','Player3'],
                  'Fifty' :[0,2,1]})

print(df1)
print(' ')
print(df2)
print(' ')
print(df3)
print(' ')
print(df4)
print(' ')
merged_df = pd.merge(pd.merge(pd.merge(df1, df2, on='Player', how='outer'), df3, on='Player', how='outer'), df4, on='Player', how='outer')
print(merged_df)'''

"import pandas as pd \n\ndf1=pd.DataFrame({'Player':['Player1','Player2','Player3','Player4'],\n                  'Scores':[88,92,63,22]})\n                  \ndf2=pd.DataFrame({'Player':['Player1','Player2','Player4'],\n                  'Wickets':[0,1,5]})\n\ndf3=pd.DataFrame({'Player':['Player4','Player2','Player3'],\n                  'Catch' :[0,2,1]})\n\ndf4=pd.DataFrame({'Player':['Player4','Player5','Player3'],\n                  'Fifty' :[0,2,1]})       \n\nprint(df1)\nprint(' ')\nprint(df2)\nprint(' ')\nprint(df3)\nprint(' ')\nprint(df4)\nprint(' ')\nmerged_df = pd.merge(pd.merge(pd.merge(df1, df2, on='Player', how='outer'), df3, on='Player', how='outer'), df4, on='Player', how='outer')\nprint(merged_df)"

In [ ]:
import pandas as pd

df1= pd.DataFrame({'Player':['Player1','Player2','Player3','Player4'],
                   'Score':[10,20,30,50]})

df2= pd.DataFrame({'Player':['Player1','Player2','Player4'],
                   'wickets':[0,3,1]})
df3=pd.DataFrame({'Player':['player4','Player3','Player1'],
                  'Catch':[0,2,1]})

print(df1)
print('')
print(df2)
print('')
print(df3)
print('')
merged_df = pd.merge(pd.merge(pd.merge(df1, df2, on='Player', how='outer'), df3, on='Player', how='outer'), df4, on='Player', how='outer')
print(merged_df)

    Player  Score
0  Player1     10
1  Player2     20
2  Player3     30
3  Player4     50

    Player  wickets
0  Player1        0
1  Player2        3
2  Player4        1

    Player  Catch
0  player4      0
1  Player3      2
2  Player1      1

    Player  Score  wickets  Catch  Fifty
0  Player1   10.0      0.0    1.0    NaN
1  Player2   20.0      3.0    NaN    NaN
2  Player3   30.0      NaN    2.0    1.0
3  Player4   50.0      1.0    NaN    0.0
4  player4    NaN      NaN    0.0    NaN
5  Player5    NaN      NaN    NaN    2.0

In [ ]:
import pandas as pd
df3=pd.DataFrame({'Key':['A','B','C','D'],
                  'Value':[1,2,3,5]})

df4=pd.DataFrame({'Key':['B','D','E','F'],
                  'Value':[5,6,7,5]})

In [ ]:
df3

  Key  Value
0   A      1
1   B      2
2   C      3
3   D      5

In [ ]:
df4

  Key  Value
0   B      5
1   D      6
2   E      7
3   F      5

In [ ]:
import pandas as pd

merged_df1 = pd.merge(df3, df4, on='Key', how='left')
print(merged_df1)

  Key  Value_x  Value_y
0   A        1      NaN
1   B        2      5.0
2   C        3      NaN
3   D        5      6.0

In [ ]:

import pandas as pd

# Create the first DataFrame
df3 = pd.DataFrame({'Key': ['A', 'B', 'C', 'D'],
                    'Value': [1, 2, 3, 5]})

# Create the second DataFrame
df4 = pd.DataFrame({'Key': ['B', 'D', 'E', 'F'],
                    'Value': [5, 6, 7, 5]})

# Merge the DataFrames on the correct column name
merged_df1 = pd.merge(df3, df4, on='Key', how='left')
print(merged_df1)

  Key  Value_x  Value_y
0   A        1      NaN
1   B        2      5.0
2   C        3      NaN
3   D        5      6.0

In [ ]:
merged_df1= pd.merge(df3, df4, on='Key', how='right')
print(merged_df1)

  Key  Value_x  Value_y
0   B      2.0        5
1   D      5.0        6
2   E      NaN        7
3   F      NaN        5

In [ ]:
#Create two pandas series and perform floordivision and check if series one is greater than or equal to another series or not.

In [ ]:
import pandas as pd
s1 = pd.Series([10, 20, 30, 40, 25])
s2 = pd.Series([5, 10, 15, 20, 50])
s3=s1.floordiv(s2)    #s3=s1//s2
print(f's3 = \n {s3}')
s4=s1>=s2
print(f's4 = \n {s4}')

s3 =
 0    2
1    2
2    2
3    2
4    0
dtype: int64
s4 =
 0     True
1     True
2     True
3     True
4    False
dtype: bool

In [ ]:
a = pd.Series((1, 2, 3, 4, 100))
b = pd.Series([10, 20, 30, 40, 100])
b.le(a)

0    False
1    False
2    False
3    False
4     True
dtype: bool

Numpy

In [ ]:
import numpy as np

In [ ]:
a = np.array([[1, 2, 3]])
print(a)
print(a.T) # T is used to transpose the vector

[[1 2 3]]
[[1]
 [2]
 [3]]

In [ ]:

# Create a 2D array (matrix)
matrix = np.array([[1, 2, 3],[7, 5, 8]])

# Transpose the matrix
transposed_matrix = matrix.T

print("Original matrix:\n", matrix)
print("Transposed matrix:\n", transposed_matrix)

Original matrix:
 [[1 2 3]
 [7 5 8]]
Transposed matrix:
 [[1 7]
 [2 5]
 [3 8]]

In [ ]:
a = np.array([[1, 6, 7],
              [4, 3, 9]])
print(a)

[[1 6 7]
 [4 3 9]]

In [ ]:
# minimum along a column
print('Min :',np.min(a,axis=0))
# maximum along a row
print('Max :',np.min(a,axis=1))
print('Mean :',np.min(a,axis=0))
print('Mean :',np.mean(a,axis=1))
print('Median :',np.median(a,axis=1))
print('Median :',np.median(a,axis=0))

Min : [1 3 7]
Max : [1 3]
Mean : [1 3 7]
Mean : [4.66666667 5.33333333]
Median : [6. 4.]
Median : [2.5 4.5 8. ]